schemaVersion: 2.1.0
attributes:
  che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
projects:
  - name: outyet
    git:
      checkoutFrom:
        revision: main
      remotes:
        origin: "https://github.com/l0rd/outyet"
components:
  - name: go-tools
    container:
      image: quay.io/eclipse/che-golang-1.14:nightly
      memoryLimit: 1024M
