schemaVersion: 2.1.0
metadata:
  name: go-web-sample
attributes:
  che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
components:
  - name: go-tools
    container:
      image: quay.io/eclipse/che-golang-1.14:nightly
      memoryLimit: 1024M
